# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems:             [jekyll-paginate,redcarpet]

# Permalinks
permalink:        pretty

# Setup
title:            韩超
tagline:          'A Jekyll theme'
description:      '用代码作画'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/hanchao
weibo:            http://weibo.com/u/1076929083
openstreetmap:    http://www.openstreetmap.org/user/hanchao
mail:             hanchao0123@hotmail.com
